name: Cloud PC Supremo (Fix)
on: workflow_dispatch

jobs:
  run-pc:
    runs-on: windows-latest
    steps:
      - name: 1. Instalacja
        shell: powershell
        run: |
          winget install "IddSampleDriver" --accept-source-agreements --accept-package-agreements
          winget install "Supremo" --accept-source-agreements --accept-package-agreements

      - name: 2. Uruchomienie
        shell: powershell
        run: |
          # Znajdujemy plik wykonywalny Supremo w systemie i go uruchamiamy
          $supremoPath = Get-ChildItem -Path "C:\Program Files*" -Filter "Supremo.exe" -Recurse | Select-Object -First 1
          Start-Process -FilePath $supremoPath.FullName
          Write-Host "Supremo uruchomione z lokalizacji: $($supremoPath.FullName)"
          Start-Sleep -Seconds 20000
