name: Cloud PC Supremo (Stabilny)
on: workflow_dispatch

jobs:
  run-pc:
    runs-on: windows-latest
    steps:
      - name: 1. Konfiguracja
        shell: powershell
        run: |
          winget install "IddSampleDriver" --accept-source-agreements --accept-package-agreements
          # Instalacja Supremo przez winget (zamiast ręcznego exe)
          winget install "Supremo" --accept-source-agreements --accept-package-agreements

      - name: 2. Start Supremo
        shell: powershell
        run: |
          # Uruchamiamy Supremo w tle
          Start-Process -FilePath "C:\Program Files (x86)\Supremo\Supremo.exe"
          Write-Host "Supremo wystartowało. Użyj ID i hasła z logów Supremo na pulpicie!"
          Start-Sleep -Seconds 20000
